// <auto-generated />
using System;
using MVC.Intro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Intro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924053008_SeedCampingTentsData")]
    partial class SeedCampingTentsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MVC.Intro.Models.CampingTent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasVentilation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWaterproof")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CampingTents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Луксозна палатка за 4-ма души с водоустойчиво покритие и вентилация",
                            Features = "Водоустойчива, Вентилация, 4-ма души",
                            HasVentilation = true,
                            ImagePath = "images/palatka1.jpg",
                            IsWaterproof = true,
                            Name = "Палатка Експлорер",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Компактна и лека палатка за 2-ма души, идеална за планински преходи",
                            Features = "Лека, Планинска, 2-ма души",
                            HasVentilation = false,
                            ImagePath = "images/palatka2.jpg",
                            IsWaterproof = true,
                            Name = "Палатка Авантюрист",
                            Price = 280.00m
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Голяма семейна палатка с две стаи и тераса за комфорт",
                            Features = "Две стаи, Тераса, 6-ма души",
                            HasVentilation = true,
                            ImagePath = "images/palatka3.jpg",
                            IsWaterproof = true,
                            Name = "Палатка Семейна",
                            Price = 620.00m
                        });
                });

            modelBuilder.Entity("MVC.Intro.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
